{% set version = "0.4.1" %}

package:
  name: pygcgopt
  version: {{ version }}

source:
  url: https://github.com/scipopt/PyGCGOpt/archive/v{{ version }}.tar.gz
  sha256: bb2fe40e98b2e27dcaf1ee6af7d683d050181d6a2e237f3c40c06b097dd2533b

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - GCGOPTDIR="${PREFIX}"

requirements:
  build:
    - python                                   # [build_platform != target_platform]
    - cross-python_{{ target_platform }}       # [build_platform != target_platform]
    - cython                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - scip >=8.0.0
    - gcg >=3.5.0
    - python
    - pip
    - cython >=0.29.21
    - pyscipopt >=4.0.0
  run:
    - python
    - pyscipopt >=4.0.0

test:
  imports:
    - pygcgopt
    - pygcgopt.gcg
  commands:
    - python -c 'import pygcgopt.gcg; pygcgopt.gcg.Model()'

about:
  home: https://github.com/scipopt/PyGCGOpt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python interface and modeling environment for GCG
  doc_url: https://scipopt.github.io/PyGCGOpt/

extra:
  recipe-maintainers:
    - jurgen-lentz
